CREATE DATABASE patty_db;
USE patties_db;

CREATE TABLE patty
(
    id` INT NOT NULL AUTO_INCREMENT,
	`patty_name` VARCHAR(255) NOT NULL,
	`devoured` BOOLEAN DEFAULT false,
	`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
